# Generated by Django 4.2.2 on 2023-07-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('gas', models.FloatField()),
                ('movement', models.BooleanField()),
                ('brightness', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
    ]
